# Generated by Django 5.2.9 on 2026-01-04 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMTG', '0002_carta_inventario_remove_inventorycard_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_mtg',
            name='correo',
        ),
    ]
