# Generated by Django 5.2.9 on 2026-01-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMTG', '0003_remove_usuario_mtg_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventario',
            name='is_sharing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventario',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
