# Generated by Django 5.2.9 on 2025-12-25 18:43

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrinting',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('set_code', models.TextField()),
                ('collector_number', models.TextField()),
                ('lang', models.TextField(default='en')),
                ('rarity', models.TextField(blank=True, null=True)),
                ('finishes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('scryfall_id', models.UUIDField(blank=True, null=True)),
                ('image_uri', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'card_printing',
                'indexes': [models.Index(fields=['set_code', 'collector_number', 'lang'], name='idx_card_printing_lookup'), models.Index(fields=['name'], name='idx_card_printing_name')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('section', models.TextField(default='A')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryCard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('finish', models.TextField(default='nonfoil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(db_column='card_uuid', on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_entries', to='appMTG.cardprinting')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='appMTG.inventory')),
            ],
            options={
                'db_table': 'inventory_card',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_cuenta', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='PriceLatest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.TextField()),
                ('price_type', models.TextField()),
                ('finish', models.TextField(default='nonfoil')),
                ('currency', models.TextField(default='USD')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('as_of', models.DateField()),
                ('card', models.ForeignKey(db_column='card_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='prices_latest', to='appMTG.cardprinting')),
            ],
            options={
                'db_table': 'price_latest',
            },
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['user'], name='idx_inventory_user'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'section'), name='uq_inventory_user_name_section'),
        ),
        migrations.AddIndex(
            model_name='inventorycard',
            index=models.Index(fields=['inventory'], name='idx_inventory_card_inventory'),
        ),
        migrations.AddIndex(
            model_name='inventorycard',
            index=models.Index(fields=['card'], name='idx_inventory_card_card'),
        ),
        migrations.AddConstraint(
            model_name='inventorycard',
            constraint=models.UniqueConstraint(fields=('inventory', 'card', 'finish'), name='uq_inventory_card'),
        ),
        migrations.AddConstraint(
            model_name='inventorycard',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_inventory_card_quantity_gt_0'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['tipo_cuenta'], name='idx_users_tipo_cuenta'),
        ),
        migrations.AddIndex(
            model_name='pricelatest',
            index=models.Index(fields=['card'], name='idx_price_latest_card'),
        ),
        migrations.AddIndex(
            model_name='pricelatest',
            index=models.Index(fields=['provider', 'price_type'], name='idx_price_latest_provider'),
        ),
        migrations.AddConstraint(
            model_name='pricelatest',
            constraint=models.UniqueConstraint(fields=('card', 'provider', 'price_type', 'finish', 'currency'), name='uq_price_latest'),
        ),
        migrations.AddConstraint(
            model_name='pricelatest',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='ck_price_latest_price_gte_0'),
        ),
    ]
