# Generated by Django 5.2.9 on 2026-01-04 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMTG', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id_scryfall', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('imagen_url', models.URLField(max_length=500)),
                ('oracle_id', models.CharField(max_length=64)),
                ('collector_number', models.IntegerField()),
                ('set_code', models.CharField(max_length=20)),
                ('type_line', models.TextField()),
            ],
            options={
                'db_table': 'cartas',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('nombre_inventario', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.RemoveField(
            model_name='inventorycard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventorycard',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='user',
        ),
        migrations.CreateModel(
            name='AlmacenCartas',
            fields=[
                ('id_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=10)),
                ('es_foil', models.BooleanField(default=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('carta', models.ForeignKey(db_column='id_scryfall', on_delete=django.db.models.deletion.CASCADE, related_name='en_inventarios', to='appMTG.carta')),
                ('inventario', models.ForeignKey(db_column='nombre_inventario', on_delete=django.db.models.deletion.CASCADE, related_name='almacen', to='appMTG.inventario')),
            ],
            options={
                'db_table': 'almacen_cartas',
            },
        ),
        migrations.CreateModel(
            name='usuario_mtg',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(db_column='id_user_d', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_mtg',
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='usuario',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='appMTG.usuario_mtg'),
        ),
        migrations.DeleteModel(
            name='PriceLatest',
        ),
        migrations.DeleteModel(
            name='CardPrinting',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryCard',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
        migrations.AddConstraint(
            model_name='almacencartas',
            constraint=models.UniqueConstraint(fields=('inventario', 'carta', 'idioma', 'es_foil'), name='uniq_inventario_carta_idioma_foil'),
        ),
    ]
