# Generated by Django 5.2.9 on 2026-02-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMTG', '0004_inventario_is_public_inventario_is_sharing_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='border_color',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='carta',
            name='full_art',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='carta',
            name='prints_search_uri',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='carta',
            name='promo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='carta',
            name='purchase_uris',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carta',
            name='scryfall_uri',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ultima_vez',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
